// content.js
(function() {
  if (window.__ghostBrowserLoaded) return;
  window.__ghostBrowserLoaded = true;

  // Initialize UI components generated by design.js
  if (!window.__createGhostBrowserUI) return;
  const ui = window.__createGhostBrowserUI();

  // Event Listeners for UI interaction
  ui.btn.addEventListener('click', (e) => {
    e.stopPropagation(); 
    ui.setBrowserVisibility(true);
  });

  ui.closeBtn.addEventListener('click', (e) => {
    e.stopPropagation();
    ui.setBrowserVisibility(false);
  });

  ui.container.addEventListener('mouseleave', (e) => e.stopPropagation());
  ui.container.addEventListener('mouseenter', (e) => e.stopPropagation());
  ui.container.addEventListener('mousemove', (e) => e.stopPropagation());

  // --- NEW FEATURE: Fast hide on double-click anywhere on the main page ---
  window.addEventListener('dblclick', (e) => {
    // If the click is inside our shadow DOM browser container, do nothing
    const host = document.getElementById('ghost-browser-shield-host');
    if (host && host.shadowRoot && host.shadowRoot.contains(e.target)) {
      return;
    }
    
    // Otherwise, close the sidebar browser
    ui.setBrowserVisibility(false);
  });
  // -----------------------------------------------------------------------

  ui.input.addEventListener('keydown', (e) => {
    e.stopPropagation(); 
    if (e.key === 'Enter') {
      let target = ui.input.value.trim();
      if (!target) return;
      
      if (!/^https?:\/\//i.test(target) && (target.includes('.') && !target.includes(' '))) {
        target = 'https://' + target;
      } else if (!/^https?:\/\//i.test(target)) {
        target = 'https://www.google.com/search?q=' + encodeURIComponent(target) + '&igu=1';
      }
      ui.viewArea.src = target;
    }
  });
})();